# Example of Fleet-enrolled Elastic Agent pre-configured with an agent policy
# for running the APM Server integration (see kibana.yml).
#
# Run with
#   docker compose \
#     -f docker-compose.yml \
#     -f extensions/fleet/fleet-compose.yml \
#     -f extensions/fleet/agent-apmserver-compose.yml \
#     up

services:
  apm-server:
    build:
      context: extensions/fleet/
      args:
        ELASTIC_VERSION: ${ELASTIC_VERSION}
    volumes:
      - apm-server:/usr/share/elastic-agent/state:Z
      - ./certs:/etc/ssl/certs
    environment:
      TZ: Asia/Ho_Chi_Minh
      FLEET_ENROLL: '1'
      FLEET_TOKEN_POLICY_NAME: Fleet Server Policy
      FLEET_INSECURE: '0'
      FLEET_CA: /etc/ssl/certs/ca.crt
      FLEET_URL: https://fleet-server:8220
      # Enrollment.
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: ${ELASTIC_PASSWORD:-}
    ports:
      - 8200:8200
    hostname: apm-server
    restart: on-failure
    networks:
      - elk
    depends_on:
      - elasticsearch
      - kibana
      - fleet-server

volumes:
  apm-server: