version: '3.9'

services:
  dvwa:
    image: vulnerables/web-dvwa
    container_name: dvwa
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - capstone-network

  juiceshop:
    image: bkimminich/juice-shop
    container_name: juiceshop
    restart: unless-stopped
    expose:
      - "3000"
    networks:
      - capstone-network

networks:
  capstone-network:
    external: true